services:
  auth:
    container_name: auth-service
    image: auth-service:hive
    build:
      context: ./services/auth-service
      target: development
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/auth-service:/app
      - auth_node_modules:/app/node_modules
  dev:
    container_name: transcenders-dev
    image: transcenders-dev:hive
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
  auth_node_modules:
