services:
  auth:
    container_name: auth-service
    image: auth-service:hive
    build:
      context: .
      dockerfile: services/auth-service/dockerfile
      target: development
    ports:
      - "3001:3000"
      - "9228:9228"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/auth-service:/workspace/services/auth-service
      - auth_node_modules:/workspace/services/auth-service/node_modules
      - auth_db:/workspace/services/auth-service/data
      - ./packages/contracts:/workspace/packages/contracts
volumes:
  auth_node_modules:
  auth_db:
